### ISSUE TITLE
Chinese hotkey is not updated

### ISSUE THREAD

**Issue by Njnngame** [alexwidua/aegis#10]
Current update, granary, village and pagoda have been moved one age earlier.

**Comment by alexwidua** [comment]
Thank you for opening the issue @Njnngame,
I'll look into it and'll update the hotkeys after the weekend.

Cheers

**Comment by Njnngame** [comment]
Thank you for such prompt reply! Looking forward to the update.

**Comment by Njnngame** [comment]
Thank you so much! Much appreciate it.
