### ISSUE TITLE
Website has been down

### ISSUE THREAD

**Issue by Taloth** [alexwidua/aegis#14]
aegis website has been down for about a week. If it's not possible to get it back up, lemme know. I can ask aoe4world to host an instance on their own servers.

**Comment by alexwidua** [comment]
Hi!
The website is still up, it's the domain that expired (because I intentionally didn't renew it).
The app is running here [https://aoe-aegis.vercel.app](https://aoe-aegis.vercel.app/)

**Comment by Taloth** [comment]
Nice, i'll get the url updated in aoe4world, thx!

**Comment by alexwidua** [comment]
Hej @Taloth,
I ended up re-newing the domain because the domain had more traffic than I initially thought (#14, #16). 
I think it makes sense to keep aoe4world pointed to the vercel domain, just wanted to give a heads up just in case.

/alex

**Comment by Taloth** [comment]
Thanks for letting me know, and yea, I agree it's best for aoe4world to point to the vercel domain.

Also, if you want to migrate traffic over time, consider using a direct from aegis.lol to the vercel domain, that'll slowly make more ppl aware of the correct domain.
