### ISSUE TITLE
website seems to be down

### ISSUE THREAD

**Issue by lackdaz** [alexwidua/aegis#16]
This site can’t be reached

www.aegis.lol took too long to respond.

Just to be sure I checked other websites and they ran fine. Probably check hosting

**Comment by alexwidua** [comment]
Hi Seth, thank you for opening the issue.

The website has been up, it was the domain that expired (I didn't renew it initially, see #14).
To my surprise the domain has more traffic than I expected, so I decided to renew it. Should work again :-)
