### ISSUE TITLE
New civilizations from DLC

### ISSUE THREAD

**Issue by mr-spacecat** [alexwidua/aegis#21]
The Sultans Ascend DLC has added 2 new civs and 4 variant civs. It would be great if this tool got an update with new content

**Comment by mr-spacecat** [comment]
What a coincidence, the #20 pull request fixes this issue. @alexwidua Please review

**Comment by alexwidua** [comment]
Thank you for your work and for keeping this project alive. Your PR #20 has been merged into master and is now [live](https://www.aegis.lol/). 

🥂 Alex
