### ISSUE TITLE
App hot key for keep is Y but game default is Z

### ISSUE THREAD

**Issue by zebfrye** [alexwidua/aegis#8]
I think the game default hot key is E -> Z but the app currently loads E - Y

**Comment by zebfrye** [comment]
Actually, maybe it just loaded the QWERTZ keyboard profile. It seemed to change back to QWERTY with a full refresh.

**Comment by reneklacan** [comment]
@zebfrye yes, this is related to https://github.com/alexwidua/aegis/issues/7

**Comment by alexwidua** [comment]
We've made some changes to how the keyboard options are presented to avoid this sorta confusion in the future. Thank you for opening this issue and I hope the most recent version fixes this! Cheers
